http:
  port: 8091

server:
  port: 9090
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: zwPK@2018
    key-password: zwPK@2018
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.89:3306/lem_app?useUnicode=true&charaterEncoding=UTF-8&useSSL=false
    username: root
    password: Wt-admin
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: "Bearer "
mybatis:
  mapper-locations: classpath:mappers/*.xml
  logging:
    level:
      com.example.demo.dao: debug
